def chose_mongolian():
    print("You step out into the arid steppes of Inner Mongolia. You feel a cold breeze and notice colorful banners surrounding a tent city in the distance")
    choice = input("Do you want to go to the city? y/n")
    if(choice == "y"):
        print("you go to the city")
        print("You realize you have no food, so you head to what looks to be the main market.")
        print("As you are walking, you get near a secluded downhill area and spot two people harassing a little girl.")
        print("You notice the girl has ears that looks like a cat, you shake this fact off and call the two dudes to get their autographs.")
        print("This gives the girl an opportunity to escape without notice. You keep in mind where she is headed.")
        print("You apologize for bothering them and for letting the girl escape and head towards where the girl was headed, the main market.")
        print("You pass by a local pawnshop and remember that you have the autographs from the two men.")

        choice1_2 = input("Do you wish to sell the autographs? y/n")
        if(choice1_2 == "y"):
            print("You talk to the store clerk.")
            print("Hey, how much do you think these could sell for?")
            print("I hand him the autographs.")
            print("Clerk: No way! You have autographs from these two? They are famous for never signing anything!")
            print("Clerk: You didn't do anything underhanded to get these did you?")
            print("No, no, of course I didn't, uhhh I just asked them for an autograph and they gave it to me!")
            print("Clerk: Alright, I'll believe you.")
            print("Clerk: Considering these are very limited, these will probably run me 4 silver coins, enough to live for a week.")
            print("You've got yourself a deal.")
            print("You walk away, relieved that you have money to buy food. You decide to go a place the clerk mentioned to you, Planders.")
            
        if(choice1_2 == "n"):
            print("The store clerk yells at you, \"Hey! what are those in your hand?\"")
            print("They're the autographs of two people off the street, why?")
            print("Clerk: Well, they are actually a one of a kind! They never give out their autographs")
            print("Clerk: How about this, I'll take them off of you for 2 silver coins a pop. Makes it 4 silvers total.")
            print("You've got yourself a deal.")
            print("You walk away, relieved that you have money to buy food. You decide to go a place the clerk mentioned to you, Planders.")
        choice1_3 = input("Welcome sir, do you wish to sit at table 5 or table 6? 5/6")
        if(choice1_3 == "5"):
            print("Right this way sir.")
            print("There is a little girl who you notice enters Planders and wave at her.")
            print("You tell the waiter, \"Hey, actually she's also with me.\"")
            print("The two of you are seated, across one another.")
            print("Waiter: What would you like to order today?")
            print("I'll take two cooked fowl.")
            print("Two cooked fowl coming right up!")
            print("The waiter leaves")
            print("???: Thank you for getting me food mister! My name is Dragar.")
            print("Don't worry about it too much, I've got enough to live for now.")
            print("The food is served")
            print("Waiter: I hope you enjoy!")
            print("Dragar stares at the food intensely")
            print("\"chuckle\" Well what are you waiting for Dragar? It's time to dig in.")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print("We share a meal that isn't necessarily delicious, but filling none the less.")
            print(" ")
            print("\"So Dragar, are you from around here? \"")
            print("Dragar: I...")
            print("She hesitates")
            print(" ")
            print(" ")
            print("Dragar: Well not exactly, I am a rare breed of human. I am half beast and half human.")
            print("Dragar lifts her hood and shows me the cat ears of hers that I noticed before.")
            print("Dragar: People like me are usually put into slavery under the Mongols.")
            print("Dragar: My family was massacred because they defied Genghis Khan.")
            print("Dragar starts tearing up")
            print("Dragar: I have now dedicated my life to getting revenge for my family.")
            print("Dragar: You really haven't been here long now have you? Any local would report me by now.")
            print("No, I'm not from around here. I'm really sorry to hear about your story. The ruler is just too cruel.")
            print("Dragar: How about you train with me to help me get revenge?")
            print("No no, If you get revenge on him, then you would be turning into the evil that you hate the most. I wouldn't want that happening to a cute girl like you.")
            print(" ")
            print(" ")
            print("Dragar: I'll... I'll consider it.")
            print("How about this? I'll treat you out for food again.")
            print("Dragar: Really?! That's a promise!")
            print("A wealthy looking man walks up to your table")
            
        if(choice1_3 == "6"):
            print("Right this way sir.")
            print("There is a little girl who you notice enters Planders and wave at her.")
            print("You tell the waiter, \"Hey, actually she's also with me.\"")
            print("The two of you are seated, across one another.")
            print("Waiter: What would you like to order today?")
            print("I'll take two cooked fowl.")
            print("Two cooked fowl coming right up!")
            print("The waiter leaves")
            print("???: Thank you for getting me food mister! My name is Dragar.")
            print("Don't worry about it too much, I've got enough to live for now.")
            print("The food is served")
            print("Waiter: I hope you enjoy!")
            print("Dragar stares at the food intensely")
            print("\"chuckle\" Well what are you waiting for Dragar? It's time to dig in.")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print("We share a meal that isn't necessarily delicious, but filling none the less.")
            print(" ")
            print("\"So Dragar, are you from around here? \"")
            print("Dragar: I...")
            print("She hesitates")
            print(" ")
            print(" ")
            print("Dragar: Well not exactly, I am a rare breed of human. I am half beast and half human.")
            print("Dragar lifts her hood and shows me the cat ears of hers that I noticed before.")
            print("Dragar: People like me are usually put into slavery under the Mongols.")
            print("Dragar: My family was massacred because they defied Genghis Khan.")
            print("Dragar starts tearing up")
            print("Dragar: I have now dedicated my life to getting revenge for my family.")
            print("Ok, ok, calm down.")
            print(" ")
            print(" ")
            print("If you take revenge, then how would that make you any better than that old fool Genghis khan? Right?")
            print("Dragar: Okay mister... but you have to treat me out to food again!")
            print("Haha, okay okay, you got me. It's a promise")
            print("A wealthy looking man walks up to your table")

    if(choice == "n"):
        print("You see a strange hooded person walking away from the tent city. The person approaches you.")
        print("You get bumped into and the person falls and is unhooded.")
        print("???: Sorry, I didn't mean to hit you.")
        print("You notice that the person is a little girl with weird looking ears, akin to a cats")
        print("You don't have to worry about it, but what's your name?")
        print("???: Oh sorry, I forgot to introduce myself, I'm Dragar.")
        print("The girl struggles to get up and I notice her pale, skinny legs.")
        print("Dragar: But anyway mister, do you have any food to spare?")

        choice2_2 = input("Yes, I do have food / No, I don't have food")
        if(choice2_2 == "Yes, I do have food"):
            print("Dragar: Really? Can I pleeeease have some?")
            print("You realize you dont have any food nor money.")
            print("Actually, sorry I don't have food on me, but we can find some for sure... probably.")
            print("Dragar: Aww, ok, follow me. I know just the spot!")
            print("Dragar leads me to the back of a restaurant named Planders.")
            print("Dragar: Here we are! my paradise.")
            print("Alright well, it's the best we've got I guess.")
            
        if(choice2_2 == "No, I don't have food"):
            print("Sorry, I dont have any food right now.")
            print("Dragar: Aww, ok then.")
            print("Dragar slowly walks away")
            print("I call out to her")
            print("Actually even if I don't have food, follow me. We can just find some food.")
            print("Dragar: Reaaaaly? Ok mister! Let's go.")
            print("I go around asking people for food to no avail.")
            print("Dragar: Wow mister, you really haven't been around here too long have you? Here follow me, I know just the place")
            print("Dragar leads me to the back of Planders, a famous restaurant.")
            print("Alright well, this is dinner then.")
        choice2_3 = input("You hesitate to eat the food. eat/hesitate")
        if(choice2_3 == "eat"):
            print("We eat a disgusting, but edible, dinner")
            print(" ")
            print(" ")
            print("I feel like I'm going to throw up...")
            print("Dragar: Don't worry, haha, you'll get used to it.")
            print(" ")
            print("Dragar takes off her hood")
            print("Dragar: You know, I'm not exactly the best person to hang around")
            print("What? Why not?")
            print("Dragar: Well, I am a rare breed of human. I am half beast and half human.")
            print("Dragar points and shows me the cat ears of hers that I noticed before.")
            print("Dragar: People like me are usually put into slavery under the Mongols.")
            print("Dragar: My family was massacred because they defied Genghis Khan.")
            print("Dragar starts tearing up")
            print("Dragar: I have now dedicated my life to getting revenge for my family.")
            print("Ok, ok, calm down.")
            print(" ")
            print(" ")
            print("If you take revenge, then how would that make you any better than that old fool Genghis khan? Right?")
            print("Dragar puts her hood back on.")
            print("An old rich man comes up to the two of you")
        if(choice2_3 == "hesitate")
            print("Dragar: Aww come on, I let you come to my secret spot and you're making that disguted face?")
            print("Alright. I'll eat it.")
            print("Dragar: Don't worry, haha, you'll get used to it.")
            print(" ")
            print("Dragar takes off her hood")
            print("Dragar: You know, I'm not exactly the best person to hang around")
            print("What? Why not?")
            print("Dragar: Well, I am a rare breed of human. I am half beast and half human.")
            print("Dragar points and shows me the cat ears of hers that I noticed before.")
            print("Dragar: People like me are usually put into slavery under the Mongols.")
            print("Dragar: My family was massacred because they defied Genghis Khan.")
            print("Dragar starts tearing up")
            print("Dragar: I have now dedicated my life to getting revenge for my family.")
            print("Ok, ok, calm down.")
            print(" ")
            print(" ")
            print("If you take revenge, then how would that make you any better than that old fool Genghis khan? Right?")
            print("Dragar puts her hood back on.")
            print("An old rich man comes up to the two of you")



